export const PURCHASE_NOTICE = 'Tickets, reservations, gift cards, food, and physical gifts are not included and, when used, are provided by the sender.';
export const PURCHASE_HELP = 'WIVELI does not purchase tickets, reservations, gift cards, or physical gifts. Attach your own ticket, QR code, or reservation if your plan needs one.';

// Both routes carry their own requirements, prompts, and starter letter.
const idea = (id, when, title, symbol, tag, caption, requirements, fields, message, freeAlternative, freeRequirements, freeFields, freeMessage) => ({ id, when, title, symbol, tag, caption, requirements, fields, message, freeAlternative, freeRequirements, freeFields, freeMessage });
export const scenarios = [
  idea('cozy', 'you need a cozy night', 'Movie night at home', '✧', 'OPTIONAL PURCHASE',
    'Tonight, the rest of the world can wait.',
    ['Pick a movie and a time', 'Prepare snacks; arrange a rental only if needed'], ['Movie', 'Snacks & drinks', 'When'],
    'Your seat next to me is reserved. Get comfortable — I’m taking care of movie night. ♡',
    'Watch a film you already have access to and bring snacks from the kitchen.',
    ['A film you can already watch', 'A cozy spot and snacks already at home'], ['Movie we already have', 'Our cozy plan'],
    'Let’s pick a film we already have, build a blanket nest, and call the snacks in our kitchen a feast. The best part is you. ♡'),
  idea('reset', 'you need a reset', 'A little reset day', '❀', 'OPTIONAL PURCHASE',
    'For when the world feels a little too loud.',
    ['Choose a place, address, and a gentle plan', 'Upload your ticket or booking if needed'], ['Place & address', 'Our little itinerary', 'When'],
    'You don’t have to do everything today. I planned a little change of scenery for us. We can take it as slowly as you need.',
    'Walk somewhere new, bring drinks from home, and find a quiet place to sit.',
    ['A free walking route', 'A meeting place and a little note'], ['Free walking route', 'Meeting place & time'],
    'Put your phone away for a little while. Let’s take drinks from home, walk somewhere new, and find a beautiful place to sit. No rush. Just us.'),
  idea('miss', 'you miss me', 'A little bit of me', '♡', 'A LITTLE PREP',
    'A tiny way to be a little closer.',
    ['A personal letter', 'Optional: a favorite photo or a voice note'], ['One thing I wish we were doing'],
    'If you opened this, I wish I could be a little closer, too. Imagine my hand in yours for a minute. You are still my favorite part of the day, even from here.',
    'Write about one small thing you miss. Photos and audio are optional.',
    ['Just a few words from you'], ['One little memory'],
    'I miss the ordinary things with you. The little looks, the comfortable silences, the way a normal day becomes ours. Keep this little piece of me until I can be there.'),
  idea('food', 'you’ve had a terrible day', 'Favorite food rescue', '☺', 'OPTIONAL PURCHASE',
    'You’ve done enough for today, love.',
    ['Plan a meal they love', 'Arrange food yourself; add order or pickup details'], ['Your favorite food', 'How I’ll arrange it', 'When & where'],
    'Today doesn’t get to have the last word. Let me take dinner off your list. You can tell me everything, or we can just eat quietly together.',
    'Make something comforting from ingredients already at home.',
    ['Check what is already in the kitchen', 'Choose a simple meal you can make'], ['What I’ll make from what we have', 'When'],
    'I’ll make us something simple from what we have at home. No effort required from you. Come as you are; I’ll put the kettle on.'),
  idea('adventure', 'you need an adventure', 'Our secret little trip', '↗', 'OPTIONAL PURCHASE',
    'Somewhere new. My favorite person.',
    ['Choose a destination and meeting time', 'Add what to bring and any tickets you purchased'], ['Secret destination & address', 'When we leave', 'What to bring'],
    'I have a little escape planned. You bring your curiosity; I’ll bring the directions. Let’s make a day we’ll talk about later.',
    'Explore a new neighborhood on foot or follow a homemade walking treasure map.',
    ['A free route within walking distance', 'A meeting time and directions'], ['Our walking treasure map', 'Meeting time', 'What to bring from home'],
    'Our adventure starts on foot. Let’s follow a new street, find something we’ve never noticed, and take the long way home.'),
  idea('picnic', 'you need some fresh air', 'A picnic for two', '❋', 'A LITTLE PREP',
    'A patch of grass with your name on it.',
    ['Choose a free outdoor spot', 'Prepare a blanket and food from home'], ['Our picnic spot', 'What I’m bringing', 'When'],
    'There’s a little spot outside waiting for us. I’ll bring a blanket and something from home. You just bring yourself.',
    'Sit in a nearby park or garden with water and snacks you already have.',
    ['A free place to sit outdoors'], ['Our free outdoor spot'],
    'Let’s take a glass of water outside and stay a little longer than usual. No perfect picnic needed. Just fresh air and you.'),
  idea('sleep', 'you can’t sleep', 'A note for the quiet hours', '☾', 'A LITTLE PREP',
    'A little company for the middle of the night.',
    ['A gentle nighttime note', 'Optional: a voice note or playlist link'], ['A little thought to rest with'],
    'Hey, night owl. Nothing needs to be solved right this second. Let your shoulders soften. I’m sending you a quiet little hug until morning.',
    'Leave a comforting letter; no recording or subscription needed.',
    ['A few calming words'], [],
    'If sleep takes its time, that’s okay. You can rest here for a moment. Think of one ordinary, lovely thing we’ll do together. I’ll meet you in the morning. ♡'),
  idea('coffee', 'you need coffee', 'Coffee & a little catch-up', '☕', 'OPTIONAL PURCHASE',
    'Your usual, and all of my attention.',
    ['Choose a café and a time', 'Arrange the coffee or attach your own gift card'], ['Our café & address', 'Your usual order', 'When'],
    'This is your invitation to a slow coffee with me. Tell me the tiny things. I want to hear all of them.',
    'Make coffee, tea, or any drink already at home and take a short walk.',
    ['A drink already at home', 'Time for a chat'], ['What’s in our mugs', 'When & where we’ll walk'],
    'Let’s make whatever we have at home and take our mugs to the window. The drink is optional. Time with you is the whole point.'),
  idea('laugh', 'you need to laugh', 'Our very unserious archive', '☺', 'A LITTLE PREP',
    'For emergency giggles only. Obviously.',
    ['An inside joke or a funny memory', 'Optional: a silly photo or video link'], ['The joke only we understand'],
    'This envelope contains absolutely no useful advice. Only a reminder that we are ridiculous together, and I wouldn’t change a thing.',
    'Retell your funniest shared moment in a few lines.',
    ['One ridiculous memory'], ['Remember when…'],
    'I was going to write something wise, but then I remembered us trying to act normal. Please imagine my most ridiculous face. Yes, that one.'),
  idea('hug', 'you need a hug', 'One unlimited hug', '♡', 'FREE',
    'No expiry date. No reason needed.',
    ['A little note', 'Decide how they can redeem their hug'], ['How to redeem your hug'],
    'ONE UNLIMITED HUG. Redeem with me whenever you like. No explaining, no fixing, no letting go before you’re ready. If we’re apart, call me and I’ll stay a while.',
    'A long-distance hug can be a quiet call or a comforting message.',
    ['A little time to be there for them'], ['How to reach me'],
    'Wrap your arms around yourself for a second. That’s my stand-in until I can do it properly. Send me a little heart and I’ll send one right back.'),
  idea('beautiful', 'you need to feel beautiful', 'Through my eyes', '✧', 'A LITTLE PREP',
    'I wish you could see what I see.',
    ['A few specific, personal compliments', 'Optional: a photo they love'], ['Little things I adore about you'],
    'You don’t have to change anything to deserve being seen with love. I notice the way you smile when you forget someone is watching. That’s one of my favorite views.',
    'Write three things you love about their expression, character, or presence.',
    ['Three sincere compliments'], ['Three things I love'],
    'There is so much beauty in the way you exist: your kindness, your laugh, the little expressions you don’t know you make. I hope you’re gentle with yourself today.'),
  idea('doubt', 'you doubt yourself', 'Things I believe about you', '☆', 'FREE',
    'Borrow my belief in you for a minute.',
    ['Write a few strengths you see in them', 'Recall a moment they kept going'], ['Things I believe about you', 'A moment you made me proud'],
    'You don’t need to have it all figured out to take the next small step. I’ve seen your courage in ordinary moments. I believe in that person, even on the days you can’t.',
    'Write a short encouragement using one real memory.',
    ['One real example of their strength'], ['I remember when you…'],
    'A difficult day isn’t the whole story of you. Let me remind you of one moment when you kept going. I’m proud of you, including right now.'),
  idea('mad', 'you’re mad at me', 'A little white flag', '⚑', 'FREE',
    'Still on your team. Even now.',
    ['An honest note that takes responsibility', 'Offer time to listen without pressure'], ['What I want to own', 'How I can make room to listen'],
    'You don’t have to stop being upset to open this. I care about how you feel, and I want to understand. When you’re ready, I’m here to listen.',
    'Write a sincere apology and offer a quiet conversation when they are ready.',
    ['An honest apology'], ['What I’m sorry for'],
    'A cute envelope doesn’t fix everything. I know that. This is me reaching out gently and making space for what you need to say.'),
  idea('disappear', 'we need to disappear for a while', 'A no-phone date', '☁', 'A LITTLE PREP',
    'Unavailable to everyone but you.',
    ['Plan an evening together', 'Choose something you can do without screens'], ['Our no-phone plan', 'When'],
    'Let’s leave our phones in another room and forget to check the time. I want an evening of being completely here with you.',
    'Talk, draw, play a game you own, or take an evening walk.',
    ['A little uninterrupted time'], ['Our free evening together'],
    'No reservations, no big plan. Just a walk, a conversation, and our phones taking the evening off. You have my attention.'),
  idea('sweet', 'you want something sweet', 'A little dessert date', '♡', 'OPTIONAL PURCHASE',
    'Something sweet for my sweetest person.',
    ['Choose a dessert or bakery', 'Arrange the treat yourself'], ['Your sweet surprise', 'Where & when'],
    'I think we deserve a little dessert date. Especially you. Let’s linger over the last bite and pretend we’re not going to share another.',
    'Make a treat with ingredients you already have, or share a sweet note.',
    ['Pantry ingredients, or just a sweet message'], ['Our pantry treat or sweet little plan'],
    'Let’s see what sweetness we can find in the kitchen. And if the cupboards are empty, here’s the sweetest thing I know: I’m so glad it’s you.'),
  idea('choice', 'you want to choose everything', 'Your day, your way', '✺', 'FREE',
    'Today’s very important decision-maker: you.',
    ['Offer choices using things you already have', 'Make time to follow their lead'], ['Food choices from home', 'Things we could do', 'Films we already have', 'Dessert or a sweet ending'],
    'Today, you call the shots: food, activity, film, the whole tiny adventure. Tell me your picks from the list below. I’m just happy to be your plus-one.',
    'Choose between a home meal, a walk, a game, or a film you already own.',
    ['A few free options and time together'], ['Your free choices'],
    'Pick our perfect ordinary day using what we already have. A walk or a game? A film or a long chat? Every option comes with me. ♡'),
  idea('surprise', 'you need a surprise', 'The mystery envelope', '✦', 'OPTIONAL PURCHASE',
    'No peeking. Okay… just this once.',
    ['Arrange your surprise', 'Attach your own ticket, gift card, or clue if needed'], ['Your surprise', 'Where to find it or how to use it'],
    'I’ve been keeping a tiny secret. Follow the clue below — there’s a little something waiting for you, chosen with a lot of love.',
    'Hide a handwritten note or make a treasure hunt using things at home.',
    ['A note hidden at home', 'A clue to find it'], ['Your treasure-hunt clue'],
    'Your surprise isn’t from a shop. It’s a little note I made just for you. Follow this clue and know that every word is yours.'),
  idea('remember', 'you want to remember us', 'A page from our story', '∞', 'A LITTLE PREP',
    'Some days are too good to forget.',
    ['Choose a shared memory', 'Optional: add a photo and your song'], ['The day, the place, the little details'],
    'Do you remember this? I keep coming back to the small details. What we said, how we laughed, how happy I was to be there with you. I’d choose that day again.',
    'Describe a favorite shared moment; no photo is needed.',
    ['A memory in your own words'], ['Our memory'],
    'We didn’t know we were making a memory. We were just being us. That’s probably why I love it so much.'),
  idea('future', 'you need something to look forward to', 'A little date with the future', '↗', 'OPTIONAL PURCHASE',
    'There are lovely things ahead of us.',
    ['Plan something for a future date', 'Attach your own event ticket or reservation if needed'], ['What we’re looking forward to', 'Date & place', 'The plan'],
    'Here’s a little bright spot to put on your calendar. Something for us, waiting just around the corner. I can’t wait to share it with you.',
    'Schedule a sunset walk, a stargazing night, or a day at home together.',
    ['A date and a free plan'], ['Our free plan', 'Date & meeting place'],
    'Let’s save a sunset for ourselves. Put this little plan on your calendar. No tickets needed — just something lovely to look forward to, together.'),
  idea('love', 'you need to know how much I love you', 'In case you ever forget', '♥', 'FREE',
    'This one is always here for you.',
    ['A letter from the heart', 'Optional: a photo or voice note'], ['One more thing I want you to know'],
    'I love you in the big moments, but mostly in all the little ones. In the ordinary afternoons. In the way I want to tell you things first. This book is one small way of saying: you matter so much to me.',
    'Write a love letter. Your words are the whole gift.',
    ['Your words, exactly as they are'], [],
    'You don’t have to earn this love by being cheerful, productive, or easy. I’m grateful for you as you are. Come back to these words whenever you need them. ♡'),
];

export function createEntry(scenario) {
  return { id: scenario.id, selected: true, when: scenario.when, title: scenario.title, symbol: scenario.symbol, caption: scenario.caption, photo: null, free: false,
    original: { message: scenario.message, details: {}, link: '', attachment: null, audio: null },
    alternative: { message: scenario.freeMessage, details: {}, link: '', attachment: null, audio: null } };
}
export function createDraft() { return { version: 1, to: '', from: '', coverPhoto: null, entries: [] }; }
export function activeContent(entry) { return entry.free ? entry.alternative : entry.original; }
export function safeLink(value) { try { const url = new URL(value); return ['https:', 'http:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } }
export function createDemo() {
  const draft = createDraft(); draft.to = 'you'; draft.from = 'me';
  draft.entries = ['miss', 'cozy', 'reset'].map(id => createEntry(scenarios.find(s => s.id === id)));
  draft.entries[1].free = true; draft.entries[2].free = true; return draft;
}
