export const couponIdeas = [
  {
    id: "breakfast-in-bed",
    title: "BREAKFAST IN BED",
    subtitle: "Wake up happier.",
    category: "food",
  },
  {
    id: "you-pick-the-movie",
    title: "YOU PICK THE MOVIE",
    subtitle: "Tonight, it's your choice.",
    category: "cozy",
  },
  {
    id: "one-long-hug",
    title: "ONE LONG HUG",
    subtitle: "No time limit.",
    category: "care",
  },
  {
    id: "date-of-your-choice",
    title: "DATE OF YOUR CHOICE",
    subtitle: "Wherever you want.",
    category: "romance",
  },
  {
    id: "no-phone-evening",
    title: "NO-PHONE EVENING",
    subtitle: "Just us.",
    category: "romance",
  },
  {
    id: "your-favorite-dinner",
    title: "YOUR FAVORITE DINNER",
    subtitle: "I'll cook or order.",
    category: "food",
  },
  {
    id: "mystery-date",
    title: "MYSTERY DATE",
    subtitle: "A surprise awaits.",
    category: "surprise",
  },
  {
    id: "one-wish",
    title: "ONE WISH",
    subtitle: "Within reason ♡",
    category: "surprise",
  },
  {
    id: "breakfast-date",
    title: "BREAKFAST DATE",
    subtitle: "Coffee, food & you.",
    category: "food",
  },
  {
    id: "midnight-drive",
    title: "MIDNIGHT DRIVE",
    subtitle: "Music on. No destination.",
    category: "romance",
  },
  {
    id: "coffee-and-a-walk",
    title: "COFFEE & A WALK",
    subtitle: "Let's wander together.",
    category: "cozy",
  },
  {
    id: "your-perfect-day",
    title: "YOUR PERFECT DAY",
    subtitle: "You make all the plans.",
    category: "surprise",
  },
  {
    id: "dessert-on-me",
    title: "DESSERT ON ME",
    subtitle: "Pick something sweet.",
    category: "food",
  },
  {
    id: "picnic-for-two",
    title: "PICNIC FOR TWO",
    subtitle: "I'll bring everything.",
    category: "romance",
  },
  {
    id: "game-night",
    title: "GAME NIGHT",
    subtitle: "You choose the game.",
    category: "fun",
  },
  {
    id: "spa-night-at-home",
    title: "SPA NIGHT AT HOME",
    subtitle: "Relax. I've got you.",
    category: "care",
  },
  {
    id: "ill-cook-tonight",
    title: "I'LL COOK TONIGHT",
    subtitle: "The kitchen is all mine.",
    category: "food",
  },
  {
    id: "one-massage",
    title: "ONE MASSAGE",
    subtitle: "Slow down and relax.",
    category: "care",
  },
  {
    id: "sunset-date",
    title: "SUNSET DATE",
    subtitle: "Let's chase the sunset.",
    category: "romance",
  },
  {
    id: "surprise-meal",
    title: "SURPRISE MEAL",
    subtitle: "Don't ask. Just be hungry.",
    category: "food",
  },
  {
    id: "lets-go-somewhere",
    title: "LET'S GO SOMEWHERE",
    subtitle: "A little escape together.",
    category: "adventure",
  },
  {
    id: "recreate-our-first-date",
    title: "RECREATE OUR FIRST DATE",
    subtitle: "Let's do it all again.",
    category: "romance",
  },
  {
    id: "your-playlist-our-night",
    title: "YOUR PLAYLIST, OUR NIGHT",
    subtitle: "You control the soundtrack.",
    category: "cozy",
  },
  {
    id: "stay-in-day",
    title: "STAY-IN DAY",
    subtitle: "No plans. No pressure.",
    category: "cozy",
  },
  {
    id: "photo-date",
    title: "PHOTO DATE",
    subtitle: "Let's make new memories.",
    category: "fun",
  },
  {
    id: "try-something-new",
    title: "TRY SOMETHING NEW",
    subtitle: "One thing we've never done.",
    category: "adventure",
  },
  {
    id: "day-off-from-chores",
    title: "A DAY OFF FROM CHORES",
    subtitle: "Today, I've got everything.",
    category: "care",
  },
  {
    id: "open-when-you-need-me",
    title: "OPEN WHEN YOU NEED ME",
    subtitle: "I'm here. Always.",
    category: "care",
  },
  {
    id: "the-yes-coupon",
    title: "THE YES COUPON",
    subtitle: "One request. The answer is yes.",
    category: "fun",
  },
  {
    id: "the-big-surprise",
    title: "THE BIG SURPRISE",
    subtitle: "You'll have to redeem it to find out.",
    category: "special",
    special: true,
  },
];

export const couponCategories = [
  { id: "all", label: "All" },
  { id: "romance", label: "Romantic" },
  { id: "cozy", label: "Cozy" },
  { id: "food", label: "Food" },
  { id: "fun", label: "Fun" },
  { id: "care", label: "Care" },
  { id: "adventure", label: "Adventure" },
  { id: "surprise", label: "Surprises" },
  { id: "special", label: "Special" },
];
