"use client";
import WishNoteMedia from './WishNoteMedia';
export default function WishOpeningCard({gift={},giftId,claimToken,completedCount=0,hasWishes=false,disabled=false,onOpen,href,buttonLabel='MAKE A WISH'}) {
 const photo=gift.attachments?.photo;
 return <article className={`openingNote theme-${gift.style||'soft'}`}>
  <header><span>WISH NOTE ♡</span><span>FOR {gift.recipientName||'YOU'}</span></header>
  <div className="intro"><p className="eyebrow">{hasWishes?'YOUR LITTLE WORLD TOGETHER':'A LITTLE SOMETHING FOR YOU'}</p><h2>{hasWishes?'Our wishes.':'Make a wish.'}</h2><p className="message">{hasWishes?`${completedCount} / ${gift.wishCount||24} wishes completed.`:gift.message||'Your wishes, our plans, and memories waiting to happen.'}</p></div>
  <div className="polaroid"><div className="photo">{photo?<WishNoteMedia giftId={giftId} claimToken={claimToken} preview={giftId?undefined:{photo}} photoOnly framed/>:<div className="emptyPhoto"><span>♡</span><small>YOUR MEMORY</small></div>}</div><p className="caption">{gift.caption||'A little moment, just for us ♡'}</p></div>
  <footer><p className="signature"><small>WITH LOVE, FROM</small><span>{gift.senderName||'Someone special'} ♡</span></p>{href?<a href={href} target="_blank" rel="noopener noreferrer">{buttonLabel} →</a>:<button type="button" disabled={disabled} onClick={onOpen}>{buttonLabel} ♡</button>}</footer>
  <style jsx>{`
  .openingNote{position:relative;box-sizing:border-box;isolation:isolate;width:100%;max-width:620px;margin:0 auto;padding:clamp(20px,5vw,40px);border:1px solid #e4cfcc;border-radius:28px;background:#f6e9e5;color:#66333f;font-family:Georgia,'Times New Roman',serif;box-shadow:0 20px 60px #00000014;}
  .theme-minimal{background:#f6f3ed;color:#38332c;border-color:#ded8ce;}.theme-film{background:#eaddc5;color:#534332;border-color:#d1bda0;}.theme-dark{background:#2e2431;color:#f6eaf0;border-color:#584657;}
  header{display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px;font:700 9px/1.6 Arial,sans-serif;letter-spacing:.14em;}header span{overflow-wrap:anywhere;max-width:100%;}.intro{text-align:center;margin:28px 0 24px;}.eyebrow{font:700 9px/1.7 Arial,sans-serif;letter-spacing:.16em;margin:0 0 12px;opacity:.7;}h2{font:400 clamp(36px,6vw,64px)/1.05 Georgia,serif;letter-spacing:-.045em;margin:0 0 16px;overflow-wrap:anywhere;}.message{font:400 16px/1.6 Georgia,serif;margin:0 auto;max-width:440px;white-space:pre-wrap;overflow-wrap:anywhere;}
  .polaroid{box-sizing:border-box;width:100%;max-width:380px;margin:0 auto;padding:12px 12px 0;background:#fffefa;box-shadow:0 8px 24px #00000021;color:#633640;}.photo{aspect-ratio:1/1;background:#eae4df;overflow:hidden;}.emptyPhoto{height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;color:#9c8680;}.emptyPhoto span{font:400 44px Georgia,serif;}.emptyPhoto small{font:700 9px Arial,sans-serif;letter-spacing:.18em;}.caption{box-sizing:border-box;min-height:66px;margin:0;padding:18px 8px 20px;text-align:center;font:italic 18px/1.45 Georgia,serif;white-space:pre-wrap;overflow-wrap:anywhere;}
  footer{display:flex;flex-direction:column;align-items:center;gap:20px;margin-top:28px;text-align:center;}.signature{margin:0;max-width:100%;overflow-wrap:anywhere;}.signature small{display:block;font:700 9px/1.6 Arial,sans-serif;letter-spacing:.14em;opacity:.65;}.signature span{display:block;margin-top:6px;font:18px/1.4 Georgia,serif;}button,a{box-sizing:border-box;max-width:100%;min-height:48px;padding:16px 26px;border:1px solid currentColor;border-radius:40px;background:transparent;color:inherit;text-decoration:none;font:700 10px/1.5 Arial,sans-serif;letter-spacing:.1em;cursor:pointer;}button:disabled{opacity:.5;cursor:default;}button:hover:not(:disabled),a:hover{background:#ffffff25;}button:focus-visible,a:focus-visible{outline:2px solid currentColor;outline-offset:4px;}
  @media(max-width:420px){.openingNote{padding:20px 16px;border-radius:22px;}.intro{margin-top:24px;}h2{font-size:40px;}.message{font-size:15px;}.polaroid{padding:9px 9px 0;}.caption{font-size:16px;}footer button,footer a{width:100%;}}
  `}</style>
 </article>;
}
