"use client";
import WishNoteMedia from './WishNoteMedia';
export default function WishAccountDetail({gift}) {
 const date=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';
 return <section className="wishHistory"><p className="eyebrow">WISH NOTE · YOUR GIFT</p><h2>For <em>{gift.recipientName}.</em></h2><p>{gift.createdCount} of {gift.wishCount} wishes made · {gift.completedCount} completed</p>
 {!gift.wishes.length&&<p>Their first wish is still to come ♡</p>}
 {gift.wishes.map(w=><article key={w.id}><div className="top"><span>{w.category?.name}</span><span>{w.completed?'COMPLETED ♡':'A LITTLE PLAN'}</span></div><h3>{w.text}</h3><dl><div><dt>When</dt><dd>{w.date}{w.time?' · '+w.time:''}{w.timeZone?' ('+w.timeZone+')':''}</dd></div>{w.place&&<div><dt>Where</dt><dd>{w.place}</dd></div>}<div><dt>Added</dt><dd>{date(w.createdAt)}</dd></div>{w.completedAt&&<div><dt>Completed</dt><dd>{date(w.completedAt)}</dd></div>}</dl>{w.memory&&<div className="memory"><p className="eyebrow">THEIR MEMORY</p><p>{w.memory.note||'A moment worth remembering ♡'}</p>{w.memory.files?.length>0&&<WishNoteMedia giftId={gift.id} wishId={w.id} revision={w.memory.updatedAt}/>}</div>}</article>)}
 <style jsx>{`.wishHistory{color:#692f3c;max-width:860px;}.eyebrow{font:700 9px/1.5 Arial,sans-serif;letter-spacing:.15em;color:#8e7874;}h2{font:400 clamp(38px,6vw,62px)/1.1 Georgia,serif;margin:18px 0;}p{line-height:1.6;}article{margin:20px 0;background:#fffaf5;border:1px solid #e2d5ce;border-radius:20px;padding:24px;overflow-wrap:anywhere;}.top{display:flex;justify-content:space-between;gap:15px;font:700 9px/1.5 Arial,sans-serif;letter-spacing:.08em;}h3{font:400 28px/1.2 Georgia,serif;margin:22px 0;}dl>div{display:grid;grid-template-columns:90px minmax(0,1fr);gap:12px;margin:12px 0;}dt{font:12px/1.6 Arial,sans-serif;color:#8e7874;}dd{font:15px/1.6 Georgia,serif;margin:0;white-space:pre-wrap;}.memory{border-top:1px dashed #d8c5bf;margin-top:20px;padding-top:18px;}`}</style></section>;
}
