import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
import assert from 'node:assert/strict';
const read=p=>readFileSync(new URL('../app/'+p,import.meta.url),'utf8');
const clean=s=>s.replace(/^import .*;\n/gm,'').replaceAll('export ','');
const OWNER='11111111-1111-4111-8111-111111111111', FILE='22222222-2222-4222-8222-222222222222';
const asset={path:`${OWNER}/gift/${FILE}.pdf`,mimeType:'application/pdf',size:1024,name:'Certificate.pdf'};
function setup(extra={}){const c=vm.createContext({URL,console,process:{env:{SUPABASE_URL:'https://db.test',SUPABASE_SECRET_KEY:'secret'}},NextResponse:{json:(body,options)=>({body,status:options?.status||200,headers:options?.headers})},...extra});vm.runInContext(clean(read('lib/coupon-attachments.js')),c);vm.runInContext(clean(read('lib/coupon-attachment-storage.js')),c);return c;}
test('supported photo, video and certificate types enforce size limits',()=>{const c=setup();assert.equal(c.attachmentSpec('photo','image/jpeg',100).extension,'jpg');assert.equal(c.attachmentSpec('video','video/mp4',50*1024*1024).extension,'mp4');assert.equal(c.attachmentSpec('gift','application/pdf',100).extension,'pdf');assert.throws(()=>c.attachmentSpec('video','video/mp4',50*1024*1024+1));assert.throws(()=>c.attachmentSpec('gift','text/html',10));assert.throws(()=>c.attachmentSpec('__proto__','image/png',10));});
test('files cannot reference another owner or traverse directories',()=>{const c=setup();assert.equal(c.validateAttachment(asset,'gift',OWNER).path,asset.path);assert.throws(()=>c.validateAttachment(asset,'gift','other'));assert.throws(()=>c.validateAttachment({...asset,path:`${OWNER}/gift/../../other.pdf`},'gift',OWNER));});
test('gift save retains only durable attachment metadata, not expired signed URLs',()=>{const c=setup();const gift={customCoupons:[{id:'movie',attachments:{gift:{...asset,url:'temporary',unknown:'secret'}}}]};c.validateCouponAttachments(gift,OWNER);assert.equal(gift.customCoupons[0].attachments.gift.path,asset.path);assert.equal(gift.customCoupons[0].attachments.gift.url,undefined);});
test('upload requires a sender session before issuing storage access',async()=>{const c=setup({requireSession:async()=>{throw Object.assign(new Error('Please sign in'),{status:401})},fetch:()=>assert.fail('must not sign')});vm.runInContext(clean(read('api/coupon-attachments/route.js')),c);const r=await c.POST({json:async()=>({})});assert.equal(r.status,401);});
test('upload URL uses a fresh path inside the authenticated sender folder',async()=>{let url;const c=setup({requireSession:async()=>({user:{id:OWNER}}),randomUUID:()=>FILE,fetch:async(u,options)=>{url=u;assert.equal(options.method,'POST');return {ok:true,json:async()=>({url:`/object/upload/sign/wiveli-coupon-attachments/${asset.path}?token=upload`})};}});vm.runInContext(clean(read('api/coupon-attachments/route.js')),c);const r=await c.POST({json:async()=>({kind:'gift',mimeType:asset.mimeType,size:asset.size,name:asset.name})});assert.equal(r.status,200);assert.ok(url.includes(asset.path));assert.equal(r.body.attachment.path,asset.path);assert.ok(r.body.uploadUrl.startsWith('https://db.test/storage/v1/object/upload/sign/'));});
test('private gift access is required before reading or signing files',async()=>{const c=setup({requireGiftAccess:async()=>{throw Object.assign(new Error('Invalid link'),{status:403})},database:()=>assert.fail('must not read'),fetch:()=>assert.fail('must not sign')});vm.runInContext(clean(read('api/gifts/[id]/attachments/route.js')),c);assert.equal((await c.GET({url:'https://site.test?couponId=movie'},{params:Promise.resolve({id:'g'})})).status,403);});
test('guest access signs the gift file without requiring an account; URLs are refreshed',async()=>{let calls=0;const c=setup({requireGiftAccess:async()=>({participants:[{role:'sender',user_id:OWNER}]}),database:async()=>[{gift_data:{customCoupons:[{id:'movie',attachments:{gift:asset}}]}}],fetch:async()=>({ok:true,json:async()=>({signedURL:`/object/sign/wiveli-coupon-attachments/${asset.path}?token=${++calls}`})})});vm.runInContext(clean(read('api/gifts/[id]/attachments/route.js')),c);const req={url:'https://site.test?couponId=movie'},params={params:Promise.resolve({id:'g'})};const a=await c.GET(req,params),b=await c.GET(req,params);assert.equal(a.status,200);assert.notEqual(a.body.attachments.gift.url,b.body.attachments.gift.url);assert.equal(a.headers['Cache-Control'],'private, no-store');});
test('tampered stored attachment cannot sign another sender file',async()=>{const c=setup({requireGiftAccess:async()=>({participants:[{role:'sender',user_id:'other'}]}),database:async()=>[{gift_data:{customCoupons:[{id:'movie',attachments:{gift:asset}}]}}],fetch:()=>assert.fail('must not sign')});vm.runInContext(clean(read('api/gifts/[id]/attachments/route.js')),c);const result=await c.GET({url:'https://site.test?couponId=movie'},{params:Promise.resolve({id:'g'})});assert.ok(result.body.attachments.gift.error);assert.equal(result.body.attachments.gift.url,undefined);});
