import {readFileSync} from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';
const read=p=>readFileSync(new URL('../app/'+p,import.meta.url),'utf8');const clean=s=>s.replace(/^import .*;\n/gm,'').replaceAll('export ','');
const input={sender:'Julia',recipient:'Sam',moments:[{id:'movie',title:'You miss movie nights',message:'Let’s watch a movie',interaction:{enabled:true,response:'Sam wants a movie night ♡'}}]};
function ctx(extra={}){const c=vm.createContext({URL,console,NextResponse:{json:(body,o)=>({body,status:o?.status||200})},...extra});vm.runInContext(clean(read('lib/coupon-attachments.js')),c);vm.runInContext(clean(read('lib/open-when.js')),c);return c;}
test('Open When sanitizes gift settings and clears forged openings and responses',()=>{const c=ctx();const g=c.normalizeOpenWhen({...input,openedMoments:[{momentId:'movie'}],responses:[{message:'fake'}]},'sender');assert.equal(g.senderName,'Julia');assert.equal(g.openedMoments.length,0);assert.equal(g.responses.length,0);for(const patch of [{moments:[]},{moments:[input.moments[0],input.moments[0]]},{sender:''},{moments:[{...input.moments[0],photo:'data:image/jpeg;base64,abc'}]}])assert.throws(()=>c.normalizeOpenWhen({...input,...patch},'sender'));});
test('gift files and custom video background must belong to the sender',()=>{const c=ctx();const file={path:'sender/video/11111111-1111-4111-8111-111111111111.mp4',mimeType:'video/mp4',size:100,name:'Movie.mp4',url:'https://expired.test'};const g=c.normalizeOpenWhen({...input,theme:{id:'custom',customBackground:file}},'sender');assert.equal(g.theme.customBackground.url,undefined);assert.throws(()=>c.normalizeOpenWhen({...input,theme:{customBackground:file}},'other'));});
function api(options={}){let gift=ctx().normalizeOpenWhen(input,'sender'),writes=0,sends=0,conflicts=options.conflicts||0;const events=[];const c=ctx({requireGiftAccess:async()=>{if(options.denied)throw Object.assign(Error('Denied'),{status:403});return {participants:[{role:'sender',user_id:'sender'}]};},currentUser:async()=>{if(options.sender)return {id:'sender'};throw Error('Guest');},connectionForUser:async()=>({telegram_chat_id:123}),sendOnce:async({payload})=>{sends++;assert.match(payload.text,/WIVELI/);if(options.botFails)throw Error('Offline');return {sent:true};},database:async(path,o)=>{if(path.startsWith('gifts?'))return [{gift_data:gift}];if(path!=='rpc/wiveli_save_letter_event')throw Error(path);writes++;const d=JSON.parse(o.body);if(conflicts-->0)return [];gift=d.p_updated;events.push(d);return [{gift_data:gift}];}});vm.runInContext(clean(read('api/gifts/[id]/open-when/events/route.js')),c);return {run:(action,details={})=>c.POST({url:'https://site.test/api',json:async()=>({action,momentId:'movie',...details})},{params:{id:'gift-id'}}),gift:()=>gift,writes:()=>writes,sends:()=>sends,events};}
test('guest opening persists atomically with Inbox event and deduplicated bot notification',async()=>{const a=api();assert.equal((await a.run('open')).status,200);const time=a.gift().openedMoments[0].openedAt;await a.run('open');assert.equal(a.writes(),1);assert.equal(a.sends(),1);assert.equal(a.events[0].p_kind,'letter-opened');assert.equal(a.gift().openedMoments[0].openedAt,time);});
test('guest response stores note and plans; forged message text is ignored',async()=>{const a=api();assert.equal((await a.run('respond')).status,400);await a.run('open');assert.equal((await a.run('respond',{note:'This film',date:'2026-12-01',time:'19:00',place:'Our cinema',message:'forged'})).status,200);const r=a.gift().responses[0];assert.equal(r.note,'This film');assert.equal(r.message,'Sam wants a movie night ♡');assert.equal(a.events[1].p_kind,'letter-response');await a.run('respond');assert.equal(a.writes(),2);assert.equal(a.sends(),2);});
test('sender preview and unauthorized requests never save or notify',async()=>{for(const options of [{sender:true},{denied:true}]){const a=api(options);const r=await a.run('open');assert.equal(r.status,options.denied?403:200);assert.equal(a.writes(),0);assert.equal(a.sends(),0);}});
test('invalid plans, unknown letters and disabled interactions cannot write',async()=>{const a=api();assert.equal((await a.run('open',{momentId:'unknown'})).status,400);await a.run('open');for(const d of [{date:'2026-02-30'},{time:'25:00'}])assert.equal((await a.run('respond',d)).status,400);a.gift().moments[0].interaction.enabled=false;assert.equal((await a.run('respond')).status,400);assert.equal(a.writes(),1);});
test('CAS conflict retries; bot failure never discards saved letter or response',async()=>{const a=api({conflicts:1});assert.equal((await a.run('open')).status,200);assert.equal(a.writes(),2);assert.equal(a.sends(),1);const b=api({botFails:true});assert.equal((await b.run('open')).status,200);assert.equal(b.gift().openedMoments.length,1);const c=api({conflicts:5});assert.equal((await c.run('open')).status,409);assert.equal(c.sends(),0);});
test('media access requires a gift token or membership and cannot sign foreign files',async()=>{for(const denied of [true,false]){let signs=0;const c=ctx({requireGiftAccess:async()=>{if(denied)throw Object.assign(Error('Denied'),{status:403});return {participants:[{role:'sender',user_id:'sender'}]};},database:async()=>[{gift_data:{...input,moments:[{...input.moments[0],photo:{path:'other/photo/11111111-1111-4111-8111-111111111111.jpg',mimeType:'image/jpeg',size:100}}]}}],attachmentStorage:async()=>{signs++;return {signedURL:'/signed'};},storageUrl:u=>u});vm.runInContext(clean(read('api/gifts/[id]/open-when/media/route.js')),c);const r=await c.GET({}, {params:{id:'gift-id'}});assert.equal(r.status,denied?403:200);assert.equal(signs,0);if(!denied)assert.equal(r.body.failed,1);}});
test('account history includes opening time and recipient reply',()=>{const c=ctx({couponIdeas:[]});vm.runInContext(clean(read('lib/account-gifts.js')),c);const data={...input,openedMoments:[{momentId:'movie',openedAt:'2026-10-02T10:00:00Z'}],responses:[{momentId:'movie',note:'Our movie'}]};const d=c.giftDetails({id:'gift-id',gift_type:'open-when',gift_data:data});assert.equal(d.openedCount,1);assert.equal(d.responseCount,1);assert.equal(d.letters[0].response.note,'Our movie');});
