import {readFileSync} from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';
const read=p=>readFileSync(new URL('../app/'+p,import.meta.url),'utf8');const clean=s=>s.replace(/^import .*;\n/gm,'').replaceAll('export ','');
const input={sender:'Julia',recipient:'Sam',memories:[{id:'one',title:'A day together',date:'2026-10-02',text:'Our memory'}]};
function ctx(extra={}){const c=vm.createContext({URL,console,NextResponse:{json:(body,o)=>({body,status:o?.status||200})},...extra});vm.runInContext(clean(read('lib/coupon-attachments.js')),c);vm.runInContext(clean(read('lib/our-story.js')),c);return c;}
test('Our Story validates fields and discards forged recipient progress',()=>{const c=ctx();const gift=c.normalizeStory({...input,views:[{memoryId:'one'}]},'sender');assert.equal(gift.recipientName,'Sam');assert.equal(gift.views.length,0);for(const patch of [{memories:[]},{memories:[input.memories[0],input.memories[0]]},{sender:''},{openingPhoto:'blob:local'},{memories:[{...input.memories[0],date:'2026-02-30'}]}])assert.throws(()=>c.normalizeStory({...input,...patch},'sender'));});
test('only sender-owned durable attachments can be included',()=>{const c=ctx();const file={path:'sender/photo/11111111-1111-4111-8111-111111111111.jpg',mimeType:'image/jpeg',size:100,name:'Us.jpg',url:'https://expired.test'};const gift=c.normalizeStory({...input,openingPhoto:file},'sender');assert.equal(gift.openingPhoto.url,undefined);assert.throws(()=>c.normalizeStory({...input,openingPhoto:file},'another'));});
function progress({denied=false,sender=false,conflicts=0}={}){let gift=ctx().normalizeStory(input,'sender'),writes=0;const c=ctx({requireGiftAccess:async()=>{if(denied)throw Object.assign(Error('Denied'),{status:403});return {participants:[{role:'sender',user_id:'sender'}]};},currentUser:async()=>{if(sender)return {id:'sender'};throw Error('Guest');},database:async(path,o)=>{if(path.startsWith('gifts?'))return [{gift_data:gift}];writes++;if(conflicts-->0)return [];gift=JSON.parse(o.body).p_updated;return [{gift_data:gift}];}});vm.runInContext(clean(read('api/gifts/[id]/our-story/progress/route.js')),c);return {run:(memoryId='one')=>c.POST({json:async()=>({memoryId})},{params:{id:'gift-id'}}),writes:()=>writes,get:()=>gift};}
test('guest views persist once and retries preserve the original viewed time',async()=>{const s=progress();assert.equal((await s.run()).status,200);const time=s.get().views[0].viewedAt;await s.run();assert.equal(s.writes(),1);assert.equal(s.get().views[0].viewedAt,time);});
test('sender preview and missing access never record recipient activity',async()=>{for(const options of [{sender:true},{denied:true}]){const s=progress(options);const r=await s.run();assert.equal(r.status,options.denied?403:200);assert.equal(s.writes(),0);}});
test('unknown memories cannot write; concurrent conflicts retry boundedly',async()=>{const s=progress();assert.equal((await s.run('unknown')).status,400);assert.equal(s.writes(),0);const retry=progress({conflicts:1});assert.equal((await retry.run()).status,200);assert.equal(retry.writes(),2);const fail=progress({conflicts:5});assert.equal((await fail.run()).status,409);assert.equal(fail.writes(),3);});
test('media reads require gift access and never sign another owner file',async()=>{for(const denied of [true,false]){let signs=0;const file={path:'other/photo/11111111-1111-4111-8111-111111111111.jpg',mimeType:'image/jpeg',size:100,name:'Us.jpg'};const c=ctx({requireGiftAccess:async()=>{if(denied)throw Object.assign(Error('Denied'),{status:403});return {participants:[{role:'sender',user_id:'sender'}]};},database:async()=>[{gift_data:{...input,openingPhoto:file}}],attachmentStorage:async()=>{signs++;return {signedURL:'/signed'};},storageUrl:u=>u});vm.runInContext(clean(read('api/gifts/[id]/our-story/media/route.js')),c);const r=await c.GET({}, {params:{id:'gift-id'}});assert.equal(r.status,denied?403:200);assert.equal(signs,0);if(!denied){assert.equal(r.body.gift.openingPhoto,null);assert.equal(r.body.failed,1);}}});
